name: Deploy Python App to Replit

on:
  push:
    branches:
      - main  # Chạy workflow khi có thay đổi trên nhánh 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Replit CLI
        run: |
          curl -fsSL https://replit.com/public/cli.sh | bash

      - name: Deploy to Replit
        run: |
          repl deploy --token ${{ secrets.REPLIT_TOKEN }} --workspace ${{ secrets.REPLIT_WORKSPACE }}
