name: Deploy to Replit

on:
  push:
    branches:
      - main  # Hoặc tên nhánh mà bạn muốn deploy từ đó

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python (hoặc Node.js, nếu ứng dụng của bạn dùng Node.js)
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Thay đổi nếu bạn sử dụng Python khác

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Nếu dùng Python, hoặc cài đặt thư viện khác tùy theo công nghệ

      - name: Deploy to Replit
        run: |
          curl -fsSL https://replit.com/public/cli.sh | bash  # Thử lại nếu Replit CLI cần thiết
          repl deploy --token ${{ secrets.REPLIT_TOKEN }} --workspace <workspace_name>

