name: Deploy to Replit

on:
  push:
    branches:
      - main  # Hoặc nhánh khác mà bạn muốn deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python (nếu dùng Python, hoặc Node.js, tùy vào công nghệ bạn sử dụng)
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Chỉnh sửa nếu bạn dùng phiên bản Python khác

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Nếu bạn sử dụng Python, hoặc cài đặt theo công nghệ khác

    - name: Deploy to Replit using GitHub API
      env:
        REPLIT_TOKEN: ${{ secrets.REPLIT_TOKEN }}  # Đảm bảo rằng bạn đã thêm REPLIT_TOKEN vào GitHub Secrets
      run: |
        curl -X POST https://replit.com/api/v0/your_endpoint_to_deploy -H "Authorization: Bearer $REPLIT_TOKEN" -d '{"source": "repo_url", "target": "replit_workspace"}'
